// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBScVkGKGHO9GWerEUYK6WEqWUgysFSEHQ',
    appId: '1:524504477991:web:343f0ab7228bcf5999f902',
    messagingSenderId: '524504477991',
    projectId: 'lista-471ce',
    authDomain: 'lista-471ce.firebaseapp.com',
    storageBucket: 'lista-471ce.firebasestorage.app',
    measurementId: 'G-XL6QXGRLTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASdgsoJPi-TQpfu5flWWGGdpIMYE6T6Ac',
    appId: '1:524504477991:android:655526af44d907b099f902',
    messagingSenderId: '524504477991',
    projectId: 'lista-471ce',
    storageBucket: 'lista-471ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmqIaM89Cx0qgtzR9HUPOqfDZkBq8IAcc',
    appId: '1:524504477991:ios:3d445161143e8f0699f902',
    messagingSenderId: '524504477991',
    projectId: 'lista-471ce',
    storageBucket: 'lista-471ce.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmqIaM89Cx0qgtzR9HUPOqfDZkBq8IAcc',
    appId: '1:524504477991:ios:3d445161143e8f0699f902',
    messagingSenderId: '524504477991',
    projectId: 'lista-471ce',
    storageBucket: 'lista-471ce.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBScVkGKGHO9GWerEUYK6WEqWUgysFSEHQ',
    appId: '1:524504477991:web:5c5792b1f15b7b0c99f902',
    messagingSenderId: '524504477991',
    projectId: 'lista-471ce',
    authDomain: 'lista-471ce.firebaseapp.com',
    storageBucket: 'lista-471ce.firebasestorage.app',
    measurementId: 'G-CEP3V73Z9Z',
  );
}